# Generated by Django 3.2.23 on 2024-02-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producer',
            name='microlot',
            field=models.BooleanField(default=False),
        ),
    ]
