# Generated by Django 3.2.23 on 2024-02-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_auto_20240217_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='microlot',
        ),
    ]
