# Generated by Django 3.2.23 on 2024-02-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_remove_producer_microlot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='image_url',
        ),
    ]
