# Generated by Django 3.2.23 on 2024-02-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0004_remove_producer_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
