# Generated by Django 3.2.23 on 2024-02-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewing_type', models.CharField(blank=True, max_length=254, null=True)),
                ('coffee_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grinding_size', models.TextField(default='')),
                ('water_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
