# Generated by Django 3.2.23 on 2024-02-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240222_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cups',
            field=models.IntegerField(default=0),
        ),
    ]
