# Generated by Django 3.2.23 on 2024-02-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
        ('products', '0007_auto_20231228_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='region',
        ),
        migrations.AlterField(
            model_name='product',
            name='producers_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producers.producer'),
        ),
    ]
