# Generated by Django 3.2.23 on 2024-02-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='microlot',
            field=models.BooleanField(default=False),
        ),
    ]
